feat: revenue and expense input pages added
cgodevs/fintech pull request #1
Opened 2022-11-17 03:36 UTC by mateusfv

2022-11-17 22:30 UTC, pedrohlucena requested changes
Código bem limpo no geral, parabéns! Só tem aquele pontinho na tela de despesa e ta safe

2022-11-17 22:30 UTC, pedrohlucena commented on fiap-fintech/src/main/WebContent/expense.html
> +        <a class="mx-1" role="button" href="#"><img class="img-fluid " src="./resources/images/return_breadcrumb.svg"></a>
O botão de voltar deve fazer o usuário retornar a tela "dashboard", acho que isso não é incumbência sua porque isso quem tem que fazer é Servlet, mas fica o alerta

2022-11-17 22:30 UTC, pedrohlucena commented on fiap-fintech/src/main/WebContent/revenue.html
> +        <a class="mx-1" role="button" href="#"><img class="img-fluid " src="./resources/images/return_breadcrumb.svg"></a>
O botão de voltar deve fazer o usuário retornar a tela "dashboard", acho que isso não é incumbência sua porque isso quem tem que fazer é Servlet, mas fica o alerta

2022-11-17 22:30 UTC, pedrohlucena commented on fiap-fintech/src/main/WebContent/expense.html
> +                <label class="revenue-input-question" for="expenseDateQuestion" href="#">Essa entrada se repete?</label>
Aqui não deveria ser "Essa despesa se repete?"

2022-11-18 13:58 UTC, cgodevs commented on fiap-fintech/src/main/WebContent/expense.html
> +        <a class="mx-1" role="button" href="#"><img class="img-fluid " src="./resources/images/return_breadcrumb.svg"></a>
creio que no caso do botão de voltar não precisa ser através da servlet, já que nenhuma operação seria feita

2022-11-18 13:59 UTC, cgodevs commented on fiap-fintech/src/main/WebContent/expense.html
> +        <a class="mx-1" role="button" href="#"><img class="img-fluid " src="./resources/images/return_breadcrumb.svg"></a>
só colocar o dashboard.jsp no href

2022-11-18 13:59 UTC, cgodevs commented on fiap-fintech/src/main/WebContent/revenue.html
> +        <a class="mx-1" role="button" href="#"><img class="img-fluid " src="./resources/images/return_breadcrumb.svg"></a>
colocar o dashboard.jsp no href

2022-11-19 13:38 UTC, cgodevs requested changes

2022-11-19 13:38 UTC, cgodevs commented on fiap-fintech/src/main/WebContent/revenue.html
> +<!DOCTYPE html>
- o campo "categoria" pode estar abaixo do campo de valor
- faltou o campo título
- para tornar um campo obrigatório, o html nos permite usar o atributo "required" dentro das tags de cada input, acrescentar o required em todos exceto descrição e "essa entrada se repete", porf?

2022-11-19 13:38 UTC, cgodevs commented on fiap-fintech/src/main/WebContent/expense.html
> +                <input class="revenue-form-text revenue-input-format" name="expenseDesc" id="expenseDesc" type="text" placeholder="descrição">
- o campo "categoria" pode estar abaixo do campo de valor
- faltou o campo título
- para tornar um campo obrigatório, o html nos permite usar o atributo "required" dentro das tags de cada input, acrescentar o required em todos exceto descrição e "essa entrada se repete", porf?

2022-11-19 13:38 UTC, cgodevs commented on fiap-fintech/src/main/WebContent/expense.html
> +                <input class="form-check-input me-1" type="checkbox" id="expenseDateQuestion">
acrescentar atributo name="fixedEntry"

2022-11-19 13:38 UTC, cgodevs commented on fiap-fintech/src/main/WebContent/revenue.html
> +                <input class="form-check-input me-1" type="checkbox" id="revenueDateQuestion">
acrescentar atributo name="fixedEntry"

2022-11-19 14:34 UTC, cgodevs approved these changes
Arrasou! 👏
Obrigada

2022-11-19 14:48 UTC, pedrohlucena approved these changes

2022-11-19 14:48 UTC, merged